
services:
  db:
    image: postgres:18-alpine3.22
    container_name: institute_erp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp_db
    ports:
      - "5500:5432"
    init: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d erp_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
