/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Department: { // root type
    code?: string | null; // String
    createdAt?: string | null; // String
    description?: string | null; // String
    id?: string | null; // String
    institutionId?: string | null; // String
    name?: string | null; // String
    updatedAt?: string | null; // String
  }
  Institution: { // root type
    address?: string | null; // String
    city?: string | null; // String
    country?: string | null; // String
    createdAt?: string | null; // String
    email?: string | null; // String
    id?: string | null; // String
    logoUrl?: string | null; // String
    name?: string | null; // String
    phone?: string | null; // String
    postalCode?: string | null; // String
    primaryColor?: string | null; // String
    state?: string | null; // String
    subscriptionEndDate?: string | null; // String
    subscriptionStatus?: string | null; // String
    type?: string | null; // String
    updatedAt?: string | null; // String
    website?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Student: { // root type
    address?: string | null; // String
    batchId?: string | null; // String
    createdAt?: string | null; // String
    currentSemester?: number | null; // Int
    currentYear?: number | null; // Int
    dateOfBirth?: string | null; // String
    departmentId?: string | null; // String
    enrollmentStatus?: string | null; // String
    firstName?: string | null; // String
    gender?: string | null; // String
    id?: string | null; // String
    lastName?: string | null; // String
    parentGuardianEmail?: string | null; // String
    parentGuardianName?: string | null; // String
    parentGuardianPhone?: string | null; // String
    phone?: string | null; // String
    studentId?: string | null; // String
    updatedAt?: string | null; // String
    userId?: string | null; // String
  }
  Teacher: { // root type
    address?: string | null; // String
    createdAt?: string | null; // String
    dateOfBirth?: string | null; // String
    departmentId?: string | null; // String
    employmentStatus?: string | null; // String
    firstName?: string | null; // String
    gender?: string | null; // String
    id?: string | null; // String
    joiningDate?: string | null; // String
    lastEvaluationDate?: string | null; // String
    lastName?: string | null; // String
    performanceScore?: number | null; // Float
    phone?: string | null; // String
    qualification?: string | null; // String
    teacherId?: string | null; // String
    updatedAt?: string | null; // String
    userId?: string | null; // String
  }
  User: { // root type
    createdAt?: string | null; // String
    email?: string | null; // String
    id?: string | null; // String
    institutionId?: string | null; // String
    isActive?: boolean | null; // Boolean
    isEmailVerified?: boolean | null; // Boolean
    lastLogin?: string | null; // String
    passwordHash?: string | null; // String
    profileImageUrl?: string | null; // String
    resetToken?: string | null; // String
    resetTokenExpires?: string | null; // String
    role?: string | null; // String
    timezone?: string | null; // String
    twoFactorEnabled?: boolean | null; // Boolean
    twoFactorSecret?: string | null; // String
    updatedAt?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Department: { // field return type
    code: string | null; // String
    createdAt: string | null; // String
    description: string | null; // String
    id: string | null; // String
    institutionId: string | null; // String
    name: string | null; // String
    teachers: Array<NexusGenRootTypes['Teacher'] | null> | null; // [Teacher]
    updatedAt: string | null; // String
  }
  Institution: { // field return type
    address: string | null; // String
    city: string | null; // String
    country: string | null; // String
    createdAt: string | null; // String
    email: string | null; // String
    id: string | null; // String
    logoUrl: string | null; // String
    name: string | null; // String
    phone: string | null; // String
    postalCode: string | null; // String
    primaryColor: string | null; // String
    state: string | null; // String
    subscriptionEndDate: string | null; // String
    subscriptionPlanId: string | null; // String
    subscriptionStatus: string | null; // String
    type: string | null; // String
    updatedAt: string | null; // String
    website: string | null; // String
  }
  Mutation: { // field return type
    createInstitution: NexusGenRootTypes['Institution'] | null; // Institution
    createUser: NexusGenRootTypes['User'] | null; // User
    deleteUser: NexusGenRootTypes['User'] | null; // User
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    department: NexusGenRootTypes['Department'] | null; // Department
    departments: Array<NexusGenRootTypes['Department'] | null> | null; // [Department]
    institution: NexusGenRootTypes['Institution'] | null; // Institution
    institutions: Array<NexusGenRootTypes['Institution'] | null> | null; // [Institution]
    student: NexusGenRootTypes['Student'] | null; // Student
    students: Array<NexusGenRootTypes['Student'] | null> | null; // [Student]
    teacher: NexusGenRootTypes['Teacher'] | null; // Teacher
    teachers: Array<NexusGenRootTypes['Teacher'] | null> | null; // [Teacher]
    user: NexusGenRootTypes['User'] | null; // User
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  Student: { // field return type
    address: string | null; // String
    batchId: string | null; // String
    createdAt: string | null; // String
    currentSemester: number | null; // Int
    currentYear: number | null; // Int
    dateOfBirth: string | null; // String
    department: NexusGenRootTypes['Department'] | null; // Department
    departmentId: string | null; // String
    enrollmentStatus: string | null; // String
    firstName: string | null; // String
    gender: string | null; // String
    id: string | null; // String
    lastName: string | null; // String
    parentGuardianEmail: string | null; // String
    parentGuardianName: string | null; // String
    parentGuardianPhone: string | null; // String
    phone: string | null; // String
    studentId: string | null; // String
    updatedAt: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
    userId: string | null; // String
  }
  Teacher: { // field return type
    address: string | null; // String
    createdAt: string | null; // String
    dateOfBirth: string | null; // String
    department: NexusGenRootTypes['Department'] | null; // Department
    departmentId: string | null; // String
    employmentStatus: string | null; // String
    firstName: string | null; // String
    gender: string | null; // String
    id: string | null; // String
    joiningDate: string | null; // String
    lastEvaluationDate: string | null; // String
    lastName: string | null; // String
    performanceScore: number | null; // Float
    phone: string | null; // String
    qualification: string | null; // String
    teacherId: string | null; // String
    updatedAt: string | null; // String
    userId: string | null; // String
  }
  User: { // field return type
    createdAt: string | null; // String
    email: string | null; // String
    id: string | null; // String
    institution: NexusGenRootTypes['Institution'] | null; // Institution
    institutionId: string | null; // String
    isActive: boolean | null; // Boolean
    isEmailVerified: boolean | null; // Boolean
    lastLogin: string | null; // String
    passwordHash: string | null; // String
    profileImageUrl: string | null; // String
    resetToken: string | null; // String
    resetTokenExpires: string | null; // String
    role: string | null; // String
    timezone: string | null; // String
    twoFactorEnabled: boolean | null; // Boolean
    twoFactorSecret: string | null; // String
    updatedAt: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Department: { // field return type name
    code: 'String'
    createdAt: 'String'
    description: 'String'
    id: 'String'
    institutionId: 'String'
    name: 'String'
    teachers: 'Teacher'
    updatedAt: 'String'
  }
  Institution: { // field return type name
    address: 'String'
    city: 'String'
    country: 'String'
    createdAt: 'String'
    email: 'String'
    id: 'String'
    logoUrl: 'String'
    name: 'String'
    phone: 'String'
    postalCode: 'String'
    primaryColor: 'String'
    state: 'String'
    subscriptionEndDate: 'String'
    subscriptionPlanId: 'String'
    subscriptionStatus: 'String'
    type: 'String'
    updatedAt: 'String'
    website: 'String'
  }
  Mutation: { // field return type name
    createInstitution: 'Institution'
    createUser: 'User'
    deleteUser: 'User'
    updateUser: 'User'
  }
  Query: { // field return type name
    department: 'Department'
    departments: 'Department'
    institution: 'Institution'
    institutions: 'Institution'
    student: 'Student'
    students: 'Student'
    teacher: 'Teacher'
    teachers: 'Teacher'
    user: 'User'
    users: 'User'
  }
  Student: { // field return type name
    address: 'String'
    batchId: 'String'
    createdAt: 'String'
    currentSemester: 'Int'
    currentYear: 'Int'
    dateOfBirth: 'String'
    department: 'Department'
    departmentId: 'String'
    enrollmentStatus: 'String'
    firstName: 'String'
    gender: 'String'
    id: 'String'
    lastName: 'String'
    parentGuardianEmail: 'String'
    parentGuardianName: 'String'
    parentGuardianPhone: 'String'
    phone: 'String'
    studentId: 'String'
    updatedAt: 'String'
    user: 'User'
    userId: 'String'
  }
  Teacher: { // field return type name
    address: 'String'
    createdAt: 'String'
    dateOfBirth: 'String'
    department: 'Department'
    departmentId: 'String'
    employmentStatus: 'String'
    firstName: 'String'
    gender: 'String'
    id: 'String'
    joiningDate: 'String'
    lastEvaluationDate: 'String'
    lastName: 'String'
    performanceScore: 'Float'
    phone: 'String'
    qualification: 'String'
    teacherId: 'String'
    updatedAt: 'String'
    userId: 'String'
  }
  User: { // field return type name
    createdAt: 'String'
    email: 'String'
    id: 'String'
    institution: 'Institution'
    institutionId: 'String'
    isActive: 'Boolean'
    isEmailVerified: 'Boolean'
    lastLogin: 'String'
    passwordHash: 'String'
    profileImageUrl: 'String'
    resetToken: 'String'
    resetTokenExpires: 'String'
    role: 'String'
    timezone: 'String'
    twoFactorEnabled: 'Boolean'
    twoFactorSecret: 'String'
    updatedAt: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createInstitution: { // args
      address?: string | null; // String
      city?: string | null; // String
      country?: string | null; // String
      email?: string | null; // String
      logoUrl?: string | null; // String
      name: string; // String!
      phone?: string | null; // String
      postalCode?: string | null; // String
      primaryColor?: string | null; // String
      state?: string | null; // String
      subscriptionEndDate?: string | null; // String
      subscriptionPlanId?: string | null; // String
      subscriptionStatus: string; // String!
      type: string; // String!
      website?: string | null; // String
    }
    createUser: { // args
      email: string; // String!
      institutionId: string; // String!
      passwordHash: string; // String!
      role?: string | null; // String
    }
    deleteUser: { // args
      id: string; // String!
    }
    updateUser: { // args
      email?: string | null; // String
      id: string; // String!
      isActive?: string | null; // String
    }
  }
  Query: {
    department: { // args
      id: string; // String!
    }
    institution: { // args
      id: string; // String!
    }
    student: { // args
      id: string; // String!
    }
    teacher: { // args
      id: string; // String!
    }
    user: { // args
      email: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}